apiCategories = ["Library Management", "Instance Retrieval"]
gitSourceBranch = "main"

[docusaurus]
tagline = "Source code management engine for Roblox."

[navbar]
title = ""

[home]
enabled = true
includeReadme = false

[navbar.logo]
alt = "Overture"
src = "/icon-dark.png"
srcDark = "/icon.png"
