name: Build and Publish Binaries
run-name: Release binaries for ${{ github.ref_name }} by @${{ github.actor }}

on:
  release:
    types: [created]

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      # Build steps
      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
      - name: Build
        run: rojo build -o Overture.rbxm
      
      # Upload steps
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: Overture.rbxm
